server:
  port: 9032
spring:
  application:
    name: service-order
  datasource:
    driverclass-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    name: root
    password: root
  redis:
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true

